### ISSUE TITLE
Proper locking is needed in schedulers

### ISSUE THREAD

**Issue by keshonok** [natsys/tempesta#236] opened 2015-09-07 10:26 UTC
Schedulers update their internal data when `.update_grp` callback is called, and that happens when a connection is established or destroyed. The internal data is used when `.sched_srv` callback is called, and that happens when client data needs to be forwarded to a back end server. Basically, it's a look up service. Update is a synchronous event, while the look up is asynchronous as multiple clients on different CPUs are looking for a back end server to send to.

And update of internal data, and a look up in that data are not serialized in any way, and that may lead (and leads) to random crashes if a back end server or two go down or go up while Tempesta is running.

Note that this is a very critical piece of code as every HTTP message needs to be delivered to a back end server. So it needs to work as fast as possible.

**Comment by krizhanovsky** [comment] 2015-09-07 19:48
Each scheduler manages consistency of its data on its own. Also lock-free techniques are used in implementation of mentioned callbacks. Deeper investigation with specification of exact race conditions in exact scheduler(-s) code  with all necessary proofs is required, probably there is no problem at all.

**Comment by krizhanovsky** [comment] 2015-09-08 17:01
Since presence of the issue is unclear, move it to 0.5

**Comment by krizhanovsky** [comment] 2015-09-15 08:54
Actually there is problem at least in RR scheduler. We faced following crash:

![seoul_sched_rr_crash](https://cloud.githubusercontent.com/assets/884694/9870917/b919481e-5b98-11e5-97d6-023b1682d223.jpg)

This is BUG_ON statement at https://github.com/natsys/tempesta/blob/master/tempesta_fw/sched/tfw_sched_rr.c#L72 .

Firstly, we do not need to check ```conn_list``` for NULL because this is an item of allocated and zeroed array.

Secondly, we have signed integer overrun: atomic_t is effectively int, so if we call the scheduler more than 2G times (not the case for this exact crash), then it goes to be negative. ```-1 % 4 == -1``` (if number f servers or connections are 4) and when we assign it to ```size_t idx```, then we get very large index and just try to read arbitrary address in memory.

Thirdly, srv->conn_list (actually TfwPeer->conn_list) is directly traversed in the scheduler, while it's protected by TfwPeer->conn_lock.  Now it's safe because we have fixed and static number of connections defined at configuration time and only one server, but the place will definitely crash as soon as we go to add/remove new connections, e.g. in dynamic reconfiguration.

Fourthly, if 2nd (index 1 in the scheduler array) is failed, then failover callback calls tfw_sg_update() and we'll skip the connection in tfw_sched_rr_update_data(), so 3rd connection goes to palce of 2nd, and 4th to 3rd (now we have 4 connections). Now conn_list->conn_n is still 4, so the last connection is presented twice in the list 

Next, there is possible failovering race condition. Let connections with indexed 1 and 2 fail on different cpus (cpu0 and cpu1 correspondingly):
1. cpu1 (is bit ahead): starts  tfw_sched_rr_update_data() and see that connection 1 is alive (cpu0 didn't mark it as failed yet) and copies it to conns[1];
2. cpu0 starts failovering and executes the full tfw_sched_rr_update_data() loop - only two connections (0 and 3) are writted to conns, cons->conn_n = 2;
3. cpu1 goes over connections 2 and 3 and writes connection 3 by index 2. It finishes with conn_n = 3.

The last my finding, I believe the reason for the crash, is that if all the connections fail (any time!), then it easily can find conn_list->conn_n = 0 and should just return NULL. Moreover, tfw_sched_http_sched_grp() handles the case and prints error (BTW warning is more appropriate here because this is bad, but expected case).

**Comment by keshonok** [comment] 2015-09-16 19:53
There's also a case where a scheduler may return a reference to a connection that has been destroyed. 

Let's take the RR scheduler, and let's say we have one server and four connections. The fourth connection goes down. The socket gets closed, then failover procedure takes action, and eventually `tfw_sched_rr_update_data()` is called in server thread. The function builds internal data structure for the scheduler that is traversed in parallel in client threads in search for next connection as a destination for client requests.

Let's say there's a client's request, and `tfw_sched_get_srv_conn()` is ready to give out the 4th connection. It's the same 4th connection that goes down, but before `tfw_sched_rr_update_data()` changes the number of connections from 4 to 3, `tfw_sched_get_srv_conn()`gives that connection to a client.

`tfw_connection_get()` is called on that connection in `tfw_sched_get_srv_conn()` to prevent it from being destroyed while it's in use by the client. However, before it can do that, the server thread that runs `tfw_sched_rr_update_data()` finishes, and then the connection gets destroyed.

All of that means that `tfw_connection_get()` may get called on a connection that is already dead. Granted, server connection instances are somewhat persistent now (they are reused for new connections), so they are not really destroyed, but that may lead to unexpected results anyway. If server connection instances were dynamically allocated and released, it it could have lead to kernel panic on a stale pointer dereference.

**Comment by krizhanovsky** [comment] 2016-01-14 12:44
Somewhat linked with #76. Server connections must be per-cpu instead of some fixed number of connections. This simplifies the scheduling algorithms as well as improves cache locality.

**Closed** 2016-02-22 20:53 UTC
Labels: bug, crucial, question
