### ISSUE TITLE
lb: backend connections hang in TIME_WAIT state after closing

### ISSUE THREAD

**Issue by vdmit11** [natsys/tempesta#62] opened 2015-02-25 11:46 UTC
Scenario:

1. start a backend server (e.g. `nc -lp 8080`)
2. start Tempesta FW
3. wait until the connection is established
4. stop the backend server
5. wait for fin_timeout (`/proc/sys/net/ipv4/tcp_fin_timeout`)
6. check that the TCP connection is released (`netstat -an | grep TIME_WAIT`)

Got:
`tcp        0      0 127.0.0.1:23112    127.0.0.1:8080         TIME_WAIT`
The connection TCP hangs in the TIME_WAIT state even when the tcp_fin_timeout is expired.

Expected:
The closed TCP connection should be released immediately without handing in the TIME_WAIT state.
Or at least, it should be released after `tcp_fin_timeout`.

The `TIME_WAIT` means that either `FIN` is not received or it is not handled correclty.
Since we run everything locally, the `FIN` is likely received, so likely it is something wrong with `FIN` handling.

**Comment by krizhanovsky** [comment] 2015-03-10 21:38
Reassign back to Dmitry - need to recheck the issue when #46 is fixed.

**Comment by keshonok** [comment] 2015-07-23 08:54
It's been a long time and lots of code changes had been made.
Unable to reproduce now.

**Closed by keshonok** 2015-07-23 08:54 UTC
Labels: bug
